name: 'NCar-Unreal-Builder'
run-name: |
  " ${{ inputs.build_config != '' && inputs.build_config || 'Development' }} 
  | ${{ inputs.platform != '' && inputs.platform || 'Linux' }} 
  | ${{ inputs.archive && 'Release  ' || 'NoRelease' }} 
  | ${{ inputs.app_version != '' && inputs.app_version || github.run_number }} "

on:
  push:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'The version of the app to be built, if empty it would be workflow run number'
        required: false
        default: ''
      environment:
        description: 'The deployment environment'
        required: true
        type: choice
        options:
          - 'DEV '
          - 'UAT '
          - 'PROD'
        default: 'DEV'
      build_config:
        description: 'Configuration to use'
        type: choice
        required: true
        options:
          - 'Development'
          - 'DebugGame  '
          - 'Shipping   '
        default: 'Development'
      platform:
        description: 'Platform to build for'
        type: choice
        required: false
        options:
          - 'Win64'
          - 'Linux'
        default: 'Linux'
      maps:
        description: 'Maps to be packaged'
        required: false
      archive:
        description: 'Whether to archive'
        type: boolean
        required: true
        default: true

env: 
  app_version: ${{ inputs.app_version !='' && inputs.app_version || '' }}
  environment: ${{ inputs.environment != '' && inputs.environment || 'DEV' }} 
  build_config: ${{ inputs.build_config !='' && inputs.build_config || 'Development' }} 
  platform: ${{ inputs.platform !='' && inputs.platform || 'Linux' }} 
  archive: ${{ inputs.archive && true || false }}
  archive_path: '${{ github.workspace }}/Output/'
  maps: ${{ inputs.maps !='' && inputs.maps || '' }}

jobs:
  clean-workspace:
    name: Clean the workflow workspace
    runs-on: [self-hosted, CICDForUnreal, Linux]

    steps:
      # Clean the workspace by deleting the old version
      - name: Clean workspace
        run: |
          echo 'Deleting existing workspace: ${{ github.workspace }} before checkout the repo to ensure the project file is fresh'
          rm -rf ${{ github.workspace }}/*

  build-app:
    name: Build unreal project
    runs-on: [self-hosted, CICDForUnreal, Linux]
    needs: clean-workspace
    outputs: 
      zip-file: ${{ steps.compress-output.outputs.output-path }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with: 
          lfs: true
          fetch-depth: 0
          repository: ${{ github.repository }}

      - name: Build cook package
        id: build-cook-package        
        env: 
          m_runUatPath: "/home/ubuntu/UE/Linux_Unreal_Engine_5.4.1/Engine/Build/BatchFiles/RunUAT.sh"
        run: |
          echo 'Project path on runner is: '${{ github.workspace }}

          m_archivePath=${{ env.archive_path }}
          if [ "${m_archivePath:-1}"!="/"];then
            m_archivePath="${{ env.archive_path }}/"
          fi

          echo 'Package archive path is: '${{ env.archive_path }}

          # Make sure there is only one uproject file in the project.
          uprojectCount=$(find .. -type f -name "*.uproject" | wc -l) 
          if [ "$uprojectCount" != 1 ]; then
            echo "::error::$uprojectCount uproejct files exist.Please make sure there is only one uproject file in the project!"
            exit 3
          fi

          # Search for *.uproject file in the upper folder and change the relative path into absolute
          uprojectPath=$(find .. -type f -name "*.uproject" | xargs -0 -I {} readlink -f {})

          if ${{ env.archive }}; then
            archiveArg="-archive -archivedirectory=${{ env.archive_path }}"
          else
            archiveArg=""
          fi

          command="${{ env.m_runUatPath }} BuildCookRun -project=$uprojectPath -clientconfig=${{ env.build_config }} -platform=${{ env.platform }} $mapsArg -clean -cook -stage -pak -package $archiveArg -encryptinifiles -noP4 -build -unattended -utf8output"

          echo -e "buildcookrun commandline is:\n"$command
          sh -c "$command"
      
      - name: Compress output
        id: compress-output
        shell: bash
        if: ${{ env.archive == 'true' }}
        run: |
          # Check archive path exist
          if [ ! -d "${{ env.archive_path }}" ]; then
            echo "Error: Package failed, archive output folder does not exist..."
            exit 2
          fi

          # Rename the archive to add the version number
          for dir in ${{ env.archive_path }}*
          do
            echo "Build cook: list files or folders: "$dir

            if ${{ env.app_version != '' }}; then
              version_version=_${{ env.app_version }}
            else
              version_version=''
            fi

            new_name="NCar_Linux""$version_version""."${{ github.run_number }}
            new_name_path="./Output/"$new_name
            echo "Build cook: Changing output folder name from: "$(basename $dir)" to: "$new_name_path
            mv "$dir" "$new_name_path"

            echo "Build cook: Compressing output files..."
            cd Output
            zip_name=$new_name".zip"
            zip_folder=$new_name/*
            zip -rqu $zip_name $zip_folder

            echo "Build cook: Unreal build cook run completed..."      
            echo "output-path=$zip_name" >> "$GITHUB_OUTPUT"
            echo "Build cook: zip file is: "$zip_name
          done

      - name: Show compress result
        if: ${{ env.archive == 'true' }}
        run: |
          echo "zip file is in: ./Output/"${{ steps.compress-output.outputs.output-path }}

      - name: Upload artifacts
        if: ${{ env.archive =='true' }}
        id: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./Output/${{ steps.compress-output.outputs.output-path }}

  deploy:
    runs-on: [self-hosted, CICDForUnreal, Linux]
    if: ${{ inputs.archive && true || false }}

    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    name: Create release
    needs: build-app
        
    env:
      artifact_path: /home/ubuntu/ci-runner-artifact/

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with: 
          path: ${{ env.artifact_path }}

      - name: Create release
        id: create_release
        run: |
          echo "Create release: Creating release..."
          if ${{ env.app_version != '' }}; then
            release_tag=${{ env.app_version }}'.'
          else
            release_tag=${{ github.run_number }}
          fi
          gh release create $release_tag${{ github.run_number }} ${{ env.artifact_path }}artifact/${{ needs.build-app.outputs.zip-file }} --generate-notes -t "Release "$release_tag
      
      - name: Clean artifact
        if: always()
        id: clean-artifact
        run: |
          echo "Deleting intermediate artifact ${{ env.artifact_path }}/artifact/${{ needs.build-app.outputs.zip-file }}..."
          rm -f ${{ env.artifact_path }}"/artifact/"${{ needs.build-app.outputs.zip-file }}