name: "NCar-Unreal-Builder"

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: "The version of the app to be built"
        required: true
        default: "0.1.2400.1"
      environment:
        description: "The deployment environment"
        required: true
        type: choice
        options:
          - "DEV"
          - "UAT"
          - "PROD"
        default: "DEV"
      changelog:
        description: "Built app changelog"
        required: true
        default: "Test"
      upload_artifacts:
        description: "Enable upload of the app artifact to Github"
        type: boolean
        default: false
      build_config:
        description: "Configuration to use"
        type: choice
        required: true
        options:
          - "Development"
          - "Debug"
          - "Shipping"
        default: "Development"
      platform:
        description: "Platform to build for"
        type: choice
        required: false
        options:
          - "Win64"
          - "Linux"
        default: "Linux"
      maps:
        description: "Maps to be packaged"
        required: false
      archive:
        description: 'Whether to archive'
        type: choice
        required: false
        options:
          - "true"
          - "false"
        default: 'false'
      archive_path:
        description: 'Archive Path'
        required: false
        default: "$HOME/ActionsOutput/"

run-name: ${{ format('App build | {0} | {1}', inputs.app_version, inputs.environment) }}

jobs:
  build-app:
      runs-on: self-hosted
        
      steps:
        # TODO: check the workspace and delete the old version
        - run: |
            echo ${{ github.action }}

        # - uses: actions/checkout@v4
        #   with: 
        #     lfs: true

        # - run: |
        #     Scripts/buildcookrun.sh \
        #     ${{ inputs.build_config }} ${{ inputs.platform }} \
        #     ${{inputs.archive}} ${{ inputs.app_version }} \
        #     ${{ inputs.archive_path }} ${{ inputs.maps}} 
