# Please adjust runner's label in every jobs' related sections to as the repository setting before running this workflow

name: 'NCar-Unreal-Builder'
run-name: |
  " ${{ inputs.build_config != '' && inputs.build_config || 'Development' }} 
  | ${{ inputs.platform != '' && inputs.platform || 'Linux' }} 
  | ${{ (inputs.archive || startsWith(github.ref, 'refs/tags')) && 'Release  ' || 'NoRelease' }} 
  | ${{ inputs.app_version != '' && inputs.app_version || startsWith(github.ref, 'refs/tags') && github.ref.tags || github.run_number }} "

on:
  push:
    branches:
      - '**'
    paths:
      - '**'
  workflow_dispatch:
    inputs:
      app_version:
        description: 'The version of the app to be built, if empty it would be workflow run number'
        required: false
        default: ''
      # environment variable might will be used in CD process to deploy artifact on specific deployment environment which is unavailable temporarily
      # environment:
      #   description: 'The deployment environment'
      #   required: true
      #   type: choice
      #   options:
      #     - 'DEV '
      #     - 'UAT '
      #     - 'PROD'
      #   default: 'DEV'
      build_config:
        description: 'Configuration to use'
        type: choice
        required: true
        options:
          - 'Development'
          - 'DebugGame  '
          - 'Shipping   '
        default: 'Development'
      platform:
        description: 'Platform to build for'
        type: choice
        required: false
        options:
          - 'Win64'
          - 'Linux'
        default: 'Linux'
      maps:
        description: 'Maps to be packaged'
        required: false
      archive:
        description: 'Whether to archive'
        type: boolean
        required: true
        default: true

env: 
  app_version: ${{ inputs.app_version !='' && inputs.app_version || '' }}
  #environment: ${{ inputs.environment != '' && inputs.environment || 'DEV' }} 
  build_config: ${{ inputs.build_config !='' && inputs.build_config || 'Development' }} 
  platform: ${{ inputs.platform !='' && inputs.platform || 'Linux' }} 
  archive: ${{ inputs.archive && true || false }}
  archive_path: '${{ github.workspace }}/Output/'
  maps: ${{ inputs.maps !='' && inputs.maps || '' }}

jobs:
  build-app:
    name: Build unreal project
    runs-on: [self-hosted, Linux, linux-x64-ue541]

    steps:
      # Clean the workspace by deleting the old version
      - name: Clean workspace
        run: |
          echo 'Deleting existing workspace: ${{ github.workspace }} before checkout the repo to ensure the project file is fresh'
          rm -rf ${{ github.workspace }}/*
          echo 'Env: whether push has tags: ${{ startsWith(github.ref, 'refs/tags') }}'
          echo 'Env: archive value: ${{ env.archive }}'

      - name: Checkout project
        uses: actions/checkout@v4
        with: 
          lfs: true
          fetch-depth: 0
          repository: ${{ github.repository }}

      - name: Build cook package
        id: build-cook-package        
        env: 
          m_runUatPath: "/home/ubuntu/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh"
        run: |
          echo 'Build cook: Project path on runner is: '${{ github.workspace }}
          echo 'Build cook: ref.tags: '${{ github.ref.tags }}
          echo 'Build cook: ref.release_tag: '${{ github.ref.release_tag }}
          echo 'Build cook: ref_name: '${{ github.ref_name }}
          echo 'Build cook: ref_type: '${{ github.ref_type }}
          echo 'Build cook: ref: '${{ github.ref }}
          echo 'Build cook: base_ref: '${{ github.base_ref }}
          echo 'Build cook: head_ref: '${{ github.head_ref }}     

          m_archivePath=${{ env.archive_path }}
          if [ "${m_archivePath:-1}"!="/"];then
            m_archivePath="${{ env.archive_path }}/"
          fi

          echo 'Package archive path is: '${{ env.archive_path }}

          # Make sure there is only one uproject file in the project.
          uprojectCount=$(find .. -type f -name "*.uproject" | wc -l) 

          if [ "$uprojectCount" != 1 ]; then
            echo "::error::$uprojectCount uproejct files exist.Please make sure there is only one uproject file in the project!"
            exit 3
          fi

          # Search for *.uproject file in the upper folder and change the relative path into absolute
          uprojectPath=$(find .. -type f -name "*.uproject" | xargs -0 -I {} readlink -f {})

          releaseArg=${{ env.archive || startsWith(github.ref, 'refs/tags') }}
          if [[ $releaseArg ]] ; then
            archiveArg="-archive -archivedirectory=${{ env.archive_path }}"
          else
            archiveArg=""
          fi

          command="${{ env.m_runUatPath }} BuildCookRun -project=$uprojectPath -clientconfig=${{ env.build_config }} -platform=${{ env.platform }} $mapsArg -clean -cook -stage -pak -package $archiveArg -encryptinifiles -noP4 -build -unattended -utf8output"

          echo -e "buildcookrun commandline is:\n"$command
          sh -c "$command"
      
      - name: Compress output
        if: env.archive=='true' || startsWith(github.ref, 'refs/tags') == 'true'
        id: compress-output
        run: |
          # Check archive path exist
          if [ ! -d "${{ env.archive_path }}" ]; then
            echo "Error: Package failed, archive output folder does not exist..."
            exit 2
          fi

          # Rename the archive to add the version number
          for dir in ${{ env.archive_path }}*
          do
            echo "Build cook: list files or folders: "$dir

            if ${{ env.app_version != '' }}; then
              version_version=_${{ env.app_version }}
            else
              version_version=''
            fi

            new_name="NCar_Linux""$version_version""."${{ github.run_number }}
            new_name_path="./Output/"$new_name
            echo "Build cook: Changing output folder name from: "$(basename $dir)" to: "$new_name_path
            mv "$dir" "$new_name_path"

            echo "Build cook: Compressing output files..."
            cd Output
            zip_name=$new_name".zip"
            zip_folder=$new_name/*
            zip -rqu $zip_name $zip_folder

            echo "Build cook: Unreal build cook run completed..."      
            echo "output-path=$zip_name" >> "$GITHUB_OUTPUT"
            echo "relese=true" >> "$GITHUB_OUTPUT"
            echo "Build cook: zip file is: "$zip_name
          done

      - name: Show compress result
        if: env.archive=='true' || startsWith(github.ref, 'refs/tags') == 'true'
        run: |
          echo "zip file is in: ./Output/"${{ steps.compress-output.outputs.output-path }}

      - name: Upload archive to S3
        if: env.archive=='true' || startsWith(github.ref, 'refs/tags') == 'true'
        run: |
          echo "Uploading to a wonderful S3 bucket."
          # upload to aws s3
          # TODO: complete the s3 url
          # aws s3 cp ./Output/${{ steps.compress-output.outputs.output-path }} s3://
         
      - name: Create release
        if: env.archive=='true' || startsWith(github.ref, 'refs/tags') == 'true'
        id: create_release
        run: |
          echo "Create release: Creating release..."

          if ${{ startsWith(github.ref, 'refs/tags') }}; then
            release_tag=$(basename ${{ github.ref }})'.'
          else
            if ${{ env.app_version != '' }}; then
              release_tag=${{ env.app_version }}'.'
            else
              release_tag=''
            fi
          fi

          # TODO: enable this except testing
          #echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token --hostname atc-github.azure.cloud.bmw
          command="gh release create '$release_tag'${{ github.run_number }} --generate-notes -t 'Release $release_tag'${{ github.run_number }} -n 'This would be the s3 url' --latest" 
          echo -e "Create release: commandline is:\n"$command
          sh -c "$command"

      - name: Clean artifact
        if: always()
        id: clean-artifact
        run: |
          echo "Deleting intermediate artifact..."
          rm -rf ${{ github.workspace }}/*

