name: 'NCar-Unreal-Builder'
run-name: App build 

on:
  push:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'The version of the app to be built, if empty it would be workflow run number'
        required: true
        default: ''
      environment:
        description: 'The deployment environment'
        required: true
        type: choice
        options:
          - 'DEV'
          - 'UAT'
          - 'PROD'
        default: 'DEV'
      build_config:
        description: 'Configuration to use'
        type: choice
        required: true
        options:
          - 'Development'
          - 'DebugGame'
          - 'Shipping'
        default: 'Development'
      platform:
        description: 'Platform to build for'
        type: choice
        required: false
        options:
          - 'Win64'
          - 'Linux'
        default: 'Linux'
      maps:
        description: 'Maps to be packaged'
        required: false
      archive:
        description: 'Whether to archive'
        type: boolean
        required: true
        default: true
      # archive_path:
      #   description: 'Archive Path'
      #   required: false
      #   default: '/home/ubuntu/ActionsOutput/'

env: 
  app_version: ${{ inputs.app_version !='' && inputs.app_version || github.run_number }}
  tag: ${{ inputs.app_version !='' && startsWith(inputs.app_version, 'v') || false }}
  environment: ${{ inputs.environment != '' && inputs.environment || 'DEV' }} 
  build_config: ${{ inputs.build_config !='' && inputs.build_config || 'Development' }} 
  platform: ${{ inputs.platform !='' && inputs.platform || 'Linux' }} 
  archive: ${{ inputs.archive && false || true }}
  archive_path: '${{ github.workspace }}/Output/'
  maps: ${{ inputs.maps !='' && inputs.maps || '' }}

jobs:
  clean-workspace:
    name: Clean the workflow workspace
    runs-on: [self-hosted, CICDForUnreal, Linux]

    steps:
      # Clean the workspace by deleting the old version
      - name: Clean workspace
        run: |
          echo 'Deleting existing workspace: ${{ github.workspace }} before checkout the repo to ensure the project file is fresh'
          rm -rf ${{ github.workspace }}/*

  build-app:
    name: Build unreal project
    runs-on: [self-hosted, CICDForUnreal, Linux]
    needs: clean-workspace
    outputs: 
      dispatch-release: ${{ steps.check-if-release-dispatch.outputs.publish_release }}
      push-release: ${{ steps.check-if-release-push.outputs.publish_release }}
      zip-file: ./Output/${{ github.env.output-path }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with: 
          lfs: true
          fetch-depth: 0
          repository: ${{ github.repository }}

      - name: Build cook package
        id: build-cook-package
        uses: ./.github/actions/buildcook
        with:
          app_version: ${{ env.app_version }} 
          environment: ${{ env.environment }} 
          build_config: ${{ env.build_config }} 
          platform: ${{ env.platform }} 
          maps: ${{ env.maps}} 
          archive: ${{ env.archive }} 
          archive_path: ${{ env.archive_path }}
      
      - name: Show build cook run output
        run: |
          echo "Build cook run output: "${{ steps.build-cook-package.outputs }}

      - name: Upload artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v4
        env: 
          build-output: ${{ steps.build-cook-package.outputs.output-path }}
        with:
          path: ./Output/${{ github.env.output-path }}
          name: NCar${{ inputs.app_version }}_${{ github.run_number }}

  deploy:
    runs-on: [self-hosted, CICDForUnreal, Linux]
    #if: ${{ needs.build-app.outputs.dispatch-release }} || ${{ needs.build-app.outputs.push-release }}

    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    name: Create release
    needs: build-app
    
    defaults:
      run:
        working-directory: ${{ env.archive_path }} 
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with: 
          path: ${{ needs.build-app.outputs.zip-file }}

      - name: Create release
        id: create_release
        run: |
          artifact-path=${{ needs.build-app.outputs.zip-file }}
          if [ -e $artifact-path ]; then
            echo "Create release: Creating release"
            gh release create ${{ env.app_version }} $artifact-path --generate-notes -t 'Release ${{ env.app_version }}'
          else
            echo "::error::Create release: Zip file doesn't exists"
          fi
